# **Homework 3 - Convolutional Neural Network**

This is the example code of homework 3 of the machine learning course by Prof. Hung-yi Lee.

In this homework, you are required to build a convolutional neural network for image classification, possibly with some advanced training tips.


There are three levels here:

**Easy**: Build a simple convolutional neural network as the baseline. (2 pts)

**Medium**: Design a better architecture or adopt different data augmentations to improve the performance. (2 pts)

**Hard**: Utilize provided unlabeled data to obtain better results. (2 pts)

## **About the Dataset**

The dataset used here is food-11, a collection of food images in 11 classes.

For the requirement in the homework, TAs slightly modified the data.
Please DO NOT access the original fully-labeled training data or testing labels.

Also, the modified dataset is for this course only, and any further distribution or commercial use is forbidden.

In [1]:
# Download the dataset
# You may choose where to download the data.

# Google Drive
!gdown --id '1awF7pZ9Dz7X1jn1_QAiKN-_v56veCEKy' --output food-11.zip

# Dropbox
# !wget https://www.dropbox.com/s/m9q6273jl3djall/food-11.zip -O food-11.zip

# MEGA
# !sudo apt install megatools
# !megadl "https://mega.nz/#!zt1TTIhK!ZuMbg5ZjGWzWX1I6nEUbfjMZgCmAgeqJlwDkqdIryfg"

# Unzip the dataset.
# This may take some time.
!unzip -q food-11.zip

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1awF7pZ9Dz7X1jn1_QAiKN-_v56veCEKy
To: /content/food-11.zip
100% 963M/963M [00:13<00:00, 70.5MB/s]


## **Import Packages**

First, we need to import packages that will be used later.

In this homework, we highly rely on **torchvision**, a library of PyTorch.

In [7]:
# Import necessary packages.
import numpy as np
import torch
import torch.nn as nn
import torchvision.transforms as transforms
from PIL import Image
# "ConcatDataset" and "Subset" are possibly useful when doing semi-supervised learning.
from torch.utils.data import ConcatDataset, DataLoader, Subset,Dataset
from torchvision.datasets import DatasetFolder

# This is for the progress bar.
from tqdm.auto import tqdm

## **Dataset, Data Loader, and Transforms**

Torchvision provides lots of useful utilities for image preprocessing, data wrapping as well as data augmentation.

Here, since our data are stored in folders by class labels, we can directly apply **torchvision.datasets.DatasetFolder** for wrapping data without much effort.

Please refer to [PyTorch official website](https://pytorch.org/vision/stable/transforms.html) for details about different transforms.

In [3]:
# It is important to do data augmentation in training.
# However, not every augmentation is useful.
# Please think about what kind of augmentation is helpful for food recognition.
train_tfm = transforms.Compose([
    # Resize the image into a fixed shape (height = width = 128)
    
    # You may add some transforms here.
    # ToTensor() should be the last one of the transforms.
   
    # add RandomResizedCrop（随机调整图像大小裁剪）
    transforms.RandomResizedCrop((128,128)),

    transforms.ToTensor(),
])

train_tfm_2 = transforms.Compose([
    transforms.Resize((128,128)),
    # add RandomHorizontalFlip(),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor()
])

train_tfm_3 = transforms.Compose([
    transforms.Resize((128,128)),
    # RandomRotation((0,360)),
    transforms.RandomRotation((0,360)),
    transforms.ToTensor()
])

# We don't need augmentations in testing and validation.
# All we need here is to resize the PIL image and transform it into Tensor.
test_tfm = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
])


In [4]:
# Batch size for training, validation, and testing.
# A greater batch size usually gives a more stable gradient.
# But the GPU memory is limited, so please adjust it carefully.
batch_size = 128

# Construct datasets.
# The argument "loader" tells how torchvision reads the data.
train_set_1 = DatasetFolder("food-11/training/labeled", loader=lambda x: Image.open(x), extensions="jpg", transform=train_tfm)
train_set_2 = DatasetFolder("food-11/training/labeled", loader=lambda x: Image.open(x), extensions="jpg", transform=train_tfm_2)
train_set_3 = DatasetFolder("food-11/training/labeled", loader=lambda x: Image.open(x), extensions="jpg", transform=train_tfm_3)
train_set_4 = DatasetFolder("food-11/training/labeled", loader=lambda x: Image.open(x), extensions="jpg", transform=test_tfm)

# the augmentation methods are .RandomResizeCrop() & RandomRotation()
#train_set = ConcatDataset([train_set_1,train_set_3])
train_set = DatasetFolder("food-11/training/labeled", loader=lambda x: Image.open(x), extensions="jpg", transform=test_tfm)

valid_set = DatasetFolder("food-11/validation", loader=lambda x: Image.open(x), extensions="jpg", transform=test_tfm)
unlabeled_set = DatasetFolder("food-11/training/unlabeled", loader=lambda x: Image.open(x), extensions="jpg", transform=train_tfm)
test_set = DatasetFolder("food-11/testing", loader=lambda x: Image.open(x), extensions="jpg", transform=test_tfm)

# Construct data loaders.
train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory=False)
valid_loader = DataLoader(valid_set, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory=False)
test_loader = DataLoader(test_set, batch_size=batch_size, shuffle=False)

## **Model**

The basic model here is simply a stack of convolutional layers followed by some fully-connected layers.

Since there are three channels for a color image (RGB), the input channels of the network must be three.
In each convolutional layer, typically the channels of inputs grow, while the height and width shrink (or remain unchanged, according to some hyperparameters like stride and padding).

Before fed into fully-connected layers, the feature map must be flattened into a single one-dimensional vector (for each image).
These features are then transformed by the fully-connected layers, and finally, we obtain the "logits" for each class.

### **WARNING -- You Must Know**
You are free to modify the model architecture here for further improvement.
However, if you want to use some well-known architectures such as ResNet50, please make sure **NOT** to load the pre-trained weights.
Using such pre-trained models is considered cheating and therefore you will be punished.
Similarly, it is your responsibility to make sure no pre-trained weights are used if you use **torch.hub** to load any modules.

For example, if you use ResNet-18 as your model:

model = torchvision.models.resnet18(pretrained=**False**) → This is fine.

model = torchvision.models.resnet18(pretrained=**True**)  → This is **NOT** allowed.

In [5]:
class Classifier(nn.Module):
    def __init__(self):
        super(Classifier, self).__init__()
        # The arguments for commonly used modules:
        # torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding)
        # torch.nn.MaxPool2d(kernel_size, stride, padding)

        # input image size: [3, 128, 128]
        self.cnn_layers = nn.Sequential(
            nn.Conv2d(3, 64, 3, 1, 1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2, 2, 0),

            nn.Conv2d(64, 128, 3, 1, 1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(2, 2, 0),

            nn.Conv2d(128, 256, 3, 1, 1),
            nn.BatchNorm2d(256),
            nn.ReLU(),
            nn.MaxPool2d(4, 4, 0),
        )
        self.fc_layers = nn.Sequential(
            nn.Linear(256 * 8 * 8, 256),
            nn.ReLU(),
            nn.Linear(256, 256),
            nn.ReLU(),
            nn.Linear(256, 11)
        )

    def forward(self, x):
        # input (x): [batch_size, 3, 128, 128]
        # output: [batch_size, 11]

        # Extract features by convolutional layers.
        x = self.cnn_layers(x)

        # The extracted feature map must be flatten before going to fully-connected layers.
        x = x.flatten(1)

        # The features are transformed by fully-connected layers to obtain the final logits.
        x = self.fc_layers(x)
        return x

## **Training**

You can finish supervised learning by simply running the provided code without any modification.

The function "get_pseudo_labels" is used for semi-supervised learning.
It is expected to get better performance if you use unlabeled data for semi-supervised learning.
However, you have to implement the function on your own and need to adjust several hyperparameters manually.

For more details about semi-supervised learning, please refer to [Prof. Lee's slides](https://speech.ee.ntu.edu.tw/~tlkagk/courses/ML_2016/Lecture/semi%20(v3).pdf).

Again, please notice that utilizing external data (or pre-trained model) for training is **prohibited**.

Construct a Pseudo Dataset class, and then you can concate the train dataset and the pseudo.
click the links for more information about how to construct a pytorch dataset: https://blog.csdn.net/rowevine/article/details/123631144

In [8]:
# inherit Dataset
class pseudo_dataset(Dataset):
    def __init__(self,unlabeled_set, indices, pseudo_labels):
        self.data = Subset(unlabeled_set,indices)
        self.target = torch.LongTensor(pseudo_labels)[indices]
    
    def __getitem__(self,index):
      if index < 0 : #Handle negative indices
            index += len(self)
      if index >= len(self):
          raise IndexError("index %d is out of bounds for axis 0 with size %d"%(index, len(self)))
      x = self.data[index][0]
      y = self.target[index].item()  
      return x,y    


In [9]:
def get_pseudo_labels(dataset, model, threshold=0.65):
    # This functions generates pseudo-labels of a dataset using given model.
    # It returns an instance of DatasetFolder containing images whose prediction confidences exceed a given threshold.
    # You are NOT allowed to use any models trained on external data for pseudo-labeling.
    device = "cuda" if torch.cuda.is_available() else "cpu"

    # Construct a data loader.
    data_loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    # Make sure the model is in eval mode.
    model.eval()
    # Define softmax function.
    softmax = nn.Softmax(dim=-1)

    #recorde the filtered result
    masks = []
    # recorde the predicted labels
    pred_labels = []


    # Iterate over the dataset by batches.
    for batch in tqdm(data_loader):
        img, _ = batch

        # Forward the data
        # Using torch.no_grad() accelerates the forward process.
        with torch.no_grad():
            logits = model(img.to(device))

        # Obtain the probability distributions by applying softmax on logits.
        probs = softmax(logits)

        # ---------- TODO ----------
        # Filter the data and construct a new dataset.
        pred_label = probs.argmax(dim=-1).tolist()
        pred_labels.extend(pred_label)

        mask = torch.max(probs,dim=1)[0] > threshold
        masks.extend(mask)
    
    indices = torch.arange(0,dataset.length)[masks]  # len
    pseudo_dataset = pseudo_dataset(dataset,indices, pseudo_labels)
    print('using {0:.2f}% unlabeld data'.format(100 * len(pseudo_dataset) / len(dataset)))

    # # Turn off the eval mode.
    model.train()
    return pseudo_dataset

In [10]:
# "cuda" only when GPUs are available.
device = "cuda" if torch.cuda.is_available() else "cpu"

# Initialize a model, and put it on the device specified.
model = Classifier().to(device)
model.device = device

# For the classification task, we use cross-entropy as the measurement of performance.
criterion = nn.CrossEntropyLoss()

# Initialize optimizer, you may fine-tune some hyperparameters such as learning rate on your own.
optimizer = torch.optim.Adam(model.parameters(), lr=0.0003, weight_decay=1e-5)

# The number of training epochs.
n_epochs = 40

# Whether to do semi-supervised learning.
do_semi = False

for epoch in range(n_epochs):
    # ---------- TODO ----------
    # In each epoch, relabel the unlabeled dataset for semi-supervised learning.
    # Then you can combine the labeled dataset and pseudo-labeled dataset for the training.
    if do_semi:
        # Obtain pseudo-labels for unlabeled data using trained model.
        pseudo_set = get_pseudo_labels(unlabeled_set, model)

        # Construct a new dataset and a data loader for training.
        # This is used in semi-supervised learning only.
        concat_dataset = ConcatDataset([train_set, pseudo_set])
        train_loader = DataLoader(concat_dataset, batch_size=batch_size, shuffle=True, num_workers=8, pin_memory=True)

    # ---------- Training ----------
    # Make sure the model is in train mode before training.
    model.train()

    # These are used to record information in training.
    train_loss = []
    train_accs = []

    # Iterate the training set by batches.
    for batch in tqdm(train_loader):

        # A batch consists of image data and corresponding labels.
        imgs, labels = batch

        # Forward the data. (Make sure data and model are on the same device.)
        logits = model(imgs.to(device))

        # Calculate the cross-entropy loss.
        # We don't need to apply softmax before computing cross-entropy as it is done automatically.
        loss = criterion(logits, labels.to(device))

        # Gradients stored in the parameters in the previous step should be cleared out first.
        optimizer.zero_grad()

        # Compute the gradients for parameters.
        loss.backward()

        # Clip the gradient norms for stable training.
        grad_norm = nn.utils.clip_grad_norm_(model.parameters(), max_norm=10)

        # Update the parameters with computed gradients.
        optimizer.step()

        # Compute the accuracy for current batch.
        acc = (logits.argmax(dim=-1) == labels.to(device)).float().mean()

        # Record the loss and accuracy.
        train_loss.append(loss.item())
        train_accs.append(acc)

    # The average loss and accuracy of the training set is the average of the recorded values.
    train_loss = sum(train_loss) / len(train_loss)
    train_acc = sum(train_accs) / len(train_accs)

    # Print the information.
    print(f"[ Train | {epoch + 1:03d}/{n_epochs:03d} ] loss = {train_loss:.5f}, acc = {train_acc:.5f}")

    # ---------- Validation ----------
    # Make sure the model is in eval mode so that some modules like dropout are disabled and work normally.
    model.eval()

    # These are used to record information in validation.
    valid_loss = []
    valid_accs = []

    # Iterate the validation set by batches.
    for batch in tqdm(valid_loader):

        # A batch consists of image data and corresponding labels.
        imgs, labels = batch

        # We don't need gradient in validation.
        # Using torch.no_grad() accelerates the forward process.
        with torch.no_grad():
          logits = model(imgs.to(device))

        # We can still compute the loss (but not the gradient).
        loss = criterion(logits, labels.to(device))

        # Compute the accuracy for current batch.
        acc = (logits.argmax(dim=-1) == labels.to(device)).float().mean()

        # Record the loss and accuracy.
        valid_loss.append(loss.item())
        valid_accs.append(acc)

    # The average loss and accuracy for entire validation set is the average of the recorded values.
    valid_loss = sum(valid_loss) / len(valid_loss)
    valid_acc = sum(valid_accs) / len(valid_accs)

    # Print the information.
    print(f"[ Valid | {epoch + 1:03d}/{n_epochs:03d} ] loss = {valid_loss:.5f}, acc = {valid_acc:.5f}")

  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 001/040 ] loss = 2.27042, acc = 0.19656


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 001/040 ] loss = 2.82129, acc = 0.11120


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 002/040 ] loss = 1.92244, acc = 0.33219


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 002/040 ] loss = 2.25978, acc = 0.19375


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 003/040 ] loss = 1.71738, acc = 0.38156


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 003/040 ] loss = 1.73826, acc = 0.38724


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 004/040 ] loss = 1.57963, acc = 0.44781


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 004/040 ] loss = 1.77603, acc = 0.36432


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 005/040 ] loss = 1.44348, acc = 0.49406


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 005/040 ] loss = 1.67751, acc = 0.41250


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 006/040 ] loss = 1.37985, acc = 0.52344


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 006/040 ] loss = 1.75968, acc = 0.42214


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 007/040 ] loss = 1.22329, acc = 0.57844


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 007/040 ] loss = 1.68028, acc = 0.42552


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 008/040 ] loss = 1.14919, acc = 0.61625


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 008/040 ] loss = 1.61911, acc = 0.40469


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 009/040 ] loss = 0.98313, acc = 0.66688


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 009/040 ] loss = 1.72505, acc = 0.44323


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 010/040 ] loss = 0.91551, acc = 0.69250


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 010/040 ] loss = 1.56701, acc = 0.50677


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 011/040 ] loss = 0.79907, acc = 0.72469


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 011/040 ] loss = 1.60200, acc = 0.47135


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 012/040 ] loss = 0.73329, acc = 0.77719


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 012/040 ] loss = 1.86966, acc = 0.42708


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 013/040 ] loss = 0.63789, acc = 0.80719


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 013/040 ] loss = 1.70277, acc = 0.45729


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 014/040 ] loss = 0.55137, acc = 0.83937


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 014/040 ] loss = 2.10700, acc = 0.40859


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 015/040 ] loss = 0.51501, acc = 0.84469


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 015/040 ] loss = 1.56154, acc = 0.51901


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 016/040 ] loss = 0.39122, acc = 0.89656


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 016/040 ] loss = 1.80420, acc = 0.48932


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 017/040 ] loss = 0.30037, acc = 0.92469


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 017/040 ] loss = 1.79482, acc = 0.47083


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 018/040 ] loss = 0.26464, acc = 0.93875


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 018/040 ] loss = 1.90202, acc = 0.45807


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 019/040 ] loss = 0.23276, acc = 0.94563


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 019/040 ] loss = 2.00316, acc = 0.45990


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 020/040 ] loss = 0.17056, acc = 0.96812


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 020/040 ] loss = 1.98087, acc = 0.47786


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 021/040 ] loss = 0.18658, acc = 0.95812


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 021/040 ] loss = 2.16163, acc = 0.39792


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 022/040 ] loss = 0.16137, acc = 0.96125


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 022/040 ] loss = 2.40709, acc = 0.42552


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 023/040 ] loss = 0.14205, acc = 0.96656


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 023/040 ] loss = 2.38051, acc = 0.45651


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 024/040 ] loss = 0.12290, acc = 0.97500


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 024/040 ] loss = 2.27035, acc = 0.43464


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 025/040 ] loss = 0.10213, acc = 0.97750


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 025/040 ] loss = 2.38424, acc = 0.46510


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 026/040 ] loss = 0.06378, acc = 0.99406


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 026/040 ] loss = 2.20837, acc = 0.47656


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 027/040 ] loss = 0.04625, acc = 0.99719


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 027/040 ] loss = 2.14268, acc = 0.49792


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 028/040 ] loss = 0.03674, acc = 0.99656


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 028/040 ] loss = 2.54325, acc = 0.43359


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 029/040 ] loss = 0.02604, acc = 0.99969


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 029/040 ] loss = 2.23566, acc = 0.48125


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 030/040 ] loss = 0.03791, acc = 0.99562


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 030/040 ] loss = 2.46434, acc = 0.45469


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 031/040 ] loss = 0.02268, acc = 0.99937


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 031/040 ] loss = 2.45104, acc = 0.46406


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 032/040 ] loss = 0.06665, acc = 0.98219


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 032/040 ] loss = 2.30913, acc = 0.47188


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 033/040 ] loss = 0.05731, acc = 0.98625


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 033/040 ] loss = 2.52401, acc = 0.47135


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 034/040 ] loss = 0.02407, acc = 0.99844


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 034/040 ] loss = 2.60534, acc = 0.44297


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 035/040 ] loss = 0.02573, acc = 0.99625


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 035/040 ] loss = 2.46098, acc = 0.45990


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 036/040 ] loss = 0.01342, acc = 0.99969


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 036/040 ] loss = 2.67321, acc = 0.47370


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 037/040 ] loss = 0.03941, acc = 0.99062


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 037/040 ] loss = 2.72847, acc = 0.45208


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 038/040 ] loss = 0.01720, acc = 0.99937


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 038/040 ] loss = 2.57715, acc = 0.47604


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 039/040 ] loss = 0.00817, acc = 1.00000


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 039/040 ] loss = 2.42927, acc = 0.49714


  0%|          | 0/25 [00:00<?, ?it/s]

[ Train | 040/040 ] loss = 0.00667, acc = 1.00000


  0%|          | 0/6 [00:00<?, ?it/s]

[ Valid | 040/040 ] loss = 2.61194, acc = 0.48516


## **Testing**

For inference, we need to make sure the model is in eval mode, and the order of the dataset should not be shuffled ("shuffle=False" in test_loader).

Last but not least, don't forget to save the predictions into a single CSV file.
The format of CSV file should follow the rules mentioned in the slides.

### **WARNING -- Keep in Mind**

Cheating includes but not limited to:
1.   using testing labels,
2.   submitting results to previous Kaggle competitions,
3.   sharing predictions with others,
4.   copying codes from any creatures on Earth,
5.   asking other people to do it for you.

Any violations bring you punishments from getting a discount on the final grade to failing the course.

It is your responsibility to check whether your code violates the rules.
When citing codes from the Internet, you should know what these codes exactly do.
You will **NOT** be tolerated if you break the rule and claim you don't know what these codes do.


In [ ]:
# Make sure the model is in eval mode.
# Some modules like Dropout or BatchNorm affect if the model is in training mode.
model.eval()

# Initialize a list to store the predictions.
predictions = []

# Iterate the testing set by batches.
for batch in tqdm(test_loader):
    # A batch consists of image data and corresponding labels.
    # But here the variable "labels" is useless since we do not have the ground-truth.
    # If printing out the labels, you will find that it is always 0.
    # This is because the wrapper (DatasetFolder) returns images and labels for each batch,
    # so we have to create fake labels to make it work normally.
    imgs, labels = batch

    # We don't need gradient in testing, and we don't even have labels to compute loss.
    # Using torch.no_grad() accelerates the forward process.
    with torch.no_grad():
        logits = model(imgs.to(device))

    # Take the class with greatest logit as prediction and record it.
    predictions.extend(logits.argmax(dim=-1).cpu().numpy().tolist())

In [ ]:
# Save predictions into the file.
with open("predict.csv", "w") as f:

    # The first row must be "Id, Category"
    f.write("Id,Category\n")

    # For the rest of the rows, each image id corresponds to a predicted class.
    for i, pred in  enumerate(predictions):
         f.write(f"{i},{pred}\n")

In [23]:
# flitrate the dataset which is a 2d tensor
test_data = torch.Tensor([[1,3],[2,4],[3,6]])
judge = test_data[:,1]>3 
out = test_data[judge]
print(judge)
print(out)

tensor([False,  True,  True])
tensor([[2., 4.],
        [3., 6.]])


In [3]:
import torch
test_data = torch.Tensor([[1,3],[4,2],[3,6]])
preds1 = torch.max(test_data,1)[1]
value = torch.max(test_data,1)[0]
mask = value > 3

preds2 = test_data.argmax(dim=-1)

indices = torch.arange(0,3)[mask]

print(mask)
print(indices)

print(preds1)
print(preds2)
# filtrate the tensor
labels = preds1[mask]
print(labels)



tensor([False,  True,  True])
tensor([1, 2])
tensor([1, 0, 1])
tensor([1, 0, 1])
tensor([0, 1])


In [14]:
# probs 是一个二维Tensor
import torch

def filtrate(probs, criterion=5):
	mask = torch.max(probs,dim=1)[0]>criterion
	filters = probs[mask]
	return filters

#输出结果
probs= torch.Tensor([[3,2],[5,7],[1,6]])
print(probs,'\n')
print(filtrate(probs))

tensor([[3., 2.],
        [5., 7.],
        [1., 6.]]) 

tensor([[5., 7.],
        [1., 6.]])
